# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/mweb_playwright_automation',
                'doc_host': 'https://mwebcode.github.io',
                'git_url': 'https://github.com/mwebcode/mweb_playwright_automation',
                'lib_path': 'mweb_playwright_automation'},
  'syms': { 'mweb_playwright_automation.core': { 'mweb_playwright_automation.core.foo': ( 'core.html#foo',
                                                                                          'mweb_playwright_automation/core.py')}}}
